# Generated by Django 5.0 on 2023-12-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customfield",
            name="data_type",
            field=models.CharField(
                choices=[("text", "Text"), ("number", "Number"), ("date", "Date")],
                max_length=50,
            ),
        ),
    ]
