# Generated by Django 5.0 on 2023-12-22 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customfield_data_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilecustomfield",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="profilecustomfield",
            name="custom_field",
        ),
        migrations.DeleteModel(
            name="CustomerProfile",
        ),
        migrations.DeleteModel(
            name="CustomField",
        ),
        migrations.DeleteModel(
            name="ProfileCustomField",
        ),
    ]
