# Generated by Django 5.0 on 2023-12-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_remove_profilecustomfield_profile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DynamicTextFieldModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_value", models.CharField(max_length=255)),
            ],
        ),
    ]
