# Generated by Django 5.0 on 2023-12-22 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DynamicTextFieldModel",
        ),
    ]
