# Generated by Django 5.0 on 2023-12-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Recent_Activities", models.IntegerField()),
                ("Purchase_History", models.IntegerField()),
                ("Account_Type", models.CharField(max_length=10)),
                ("Money_on_Account", models.FloatField()),
                ("Age", models.IntegerField()),
                ("Monthly_Income", models.FloatField()),
                ("Credit_Score", models.IntegerField()),
                ("Number_of_Dependents", models.IntegerField()),
                ("Education_Level", models.CharField(max_length=20)),
                ("Gender", models.CharField(max_length=10)),
                ("Services_Taken", models.CharField(max_length=100)),
            ],
        ),
    ]
